### ISSUE TITLE
后期会不会切换至官方支持的 go mod 包管理工具呢？

### ISSUE THREAD

**Issue by skiy** [micro-plat/hydra#3]
如题。
目前很多项目都使用 ```go mod``` ，不知道这边会不会也替换包管理工具呢？

**Comment by wule61** [comment]
现在可以使用hydra项目创建工具gaea创建支持go mod的项目
命令: `gaea api create -n ./apiserver -mod`
gaea 地址:https://github.com/micro-plat/gaea
